services:

  # PostgreSQL 数据库服务
  postgres:
    image: postgres:16-alpine
    container_name: csm-postgres
    environment:
      POSTGRES_DB: cloud_server
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d cloud_server"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis服务
  redis:
    image: redis:7.4-alpine
    container_name: csm-redis
    volumes:
      - redisdata:/data
    restart: always
    environment:
      - TZ=Asia/Shanghai
    command: ['redis-server','--appendonly', 'yes']
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s
      timeout: 3s
      retries: 5

  # 后端服务
  backend:
    build: ./backend/cloud-server-manager
    container_name: csm-backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: cloud_server
      DB_USERNAME: root
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # 前端服务
  frontend:
    build: ./frontend/cloud-server-manager
    container_name: csm-frontend
    depends_on:
      - backend
    ports:
      - target: 80
        published: 81

volumes:
  pgdata:
  redisdata: