networks:
  default:
    name: shiny-cloud
    driver: bridge

services:

  # PostgreSQL 数据库服务
  postgres:
    image: postgres:16-alpine
    container_name: csm-postgres
    environment:
      POSTGRES_DB: cloud_server
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d cloud_server"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis服务
  redis:
    image: redis:7.4-alpine
    container_name: csm-redis
    volumes:
      - redisdata:/data
    restart: always
    environment:
      - TZ=Asia/Shanghai
    command: ['redis-server','--appendonly', 'yes']
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s
      timeout: 3s
      retries: 5

  nacos:
    image: nacos/nacos-server:v3.1.1
    container_name: csm-nacos
    environment:
      MODE: standalone
      # 开启鉴权
      NACOS_AUTH_ENABLE: "true"
      # 鉴权相关密钥
      NACOS_AUTH_TOKEN: -SecretKey012345678901234567890123456789012345678901234567890123456789
      NACOS_AUTH_IDENTITY_KEY: -serverIdentity
      NACOS_AUTH_IDENTITY_VALUE: -security
      TIME_ZONE: Asia/Shanghai
    ports:
      - "10086:8080"    # Nacos 控制台端口映射
      - "8848:8848"    # Nacos 服务端口映射
      - "9848:9848"    # Nacos gRPC 端口映射
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/index.html"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  # 网关层
  gateway:
    build:
      context: ./shiny-cloud-backend
      dockerfile: gateway/Dockerfile
    container_name: csm-gateway
    depends_on:
      nacos:
        condition: service_healthy
    environment:
      NACOS_ADDR: nacos:8848
      # 记得先去 Nacos 控制台初始化一下密码，然后在这里配置
      # 如果还是遇到了服务连不上Nacos的情况，就重新启动一下服务
      NACOS_USERNAME: nacos
      NACOS_PASSWORD: nacos
    ports:
      - target: 8080
        published: 8080

  # 后端服务
  service:
    build: 
      context: ./shiny-cloud-backend
      dockerfile: service/Dockerfile
    container_name: csm-service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nacos:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: cloud_server
      DB_USERNAME: root
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # 记得先去 Nacos 控制台初始化一下密码，然后在这里配置
      # 如果还是遇到了服务连不上Nacos的情况，就重新启动一下服务
      NACOS_ADDR: nacos:8848
      NACOS_USERNAME: nacos
      NACOS_PASSWORD: nacos

  # 前端服务
  frontend:
    build: ./shiny-cloud-frontend
    container_name: csm-frontend
    depends_on:
      - gateway
    ports:
      - target: 80
        published: 80

volumes:
  pgdata:
  redisdata: