spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}

    gateway:
      server:
        webflux:
          routes:
            # 目前未做项目分离，将所有路径都发往service
            - id: service
              uri: lb://service
              predicates:
                - Path=/**
