spring:
  application:
    name: user-service

  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}

    datasource:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cloud_server}
      driver-class-name: org.postgresql.Driver
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:postgres}