spring:
  application:
    name: cloud-server-manager
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cloud_server}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:postgres}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true

jwt:
  secret: ${JWT_SECRET:maimai_green_orange_pink_murasaki_milk_finale_dx_splash_universe_festival_buddies_prism_circle}
  expiration: ${JWT_EXPIRATION:86400000}
  