spring:
  application:
    name: cloud-server-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_server
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  